### ISSUE TITLE
Bug: Fail when users register for events

### ISSUE THREAD

**Issue by losolio** [losol/eventuras#349]
When an user tries to register for a new event in production, it throws an exception. 

```
An exception occurred while iterating over the results of a query for context type 'losol.EventManagement.Infrastructure.ApplicationDbContext'.
System.InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

https://sentry.io/share/issue/ea36b813ded147f9a5c50ca078c2d71b/

**Comment by andy-a-o** [comment]
checking

**Comment by andy-a-o** [comment]
@losolio can't reproduce it using Integration Test environment. What's the steps to reproduce it using UI?

**Comment by losolio** [comment]
Me neither can reproduce it in dev environment. This is the second exception, which might be related: 

https://sentry.io/share/issue/65bfb495f12c4d23b1dd97d8c4047a36/

**Comment by andy-a-o** [comment]
@losolio second exception - caused by two users with the same email in database. Is it a legal case? I guess not. If so, we need to remove duplicate user from db and maybe add unique index on Email + index filter like "WHERE Email IS NOT NULL AND Archived = 0" but it's better to add it after move to Postgresql. For now, removing duplicate record is enough.
